/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        background: 'var(--background, #0b1326)',
        'on-background': 'var(--on-background, #dae2fd)',
        'surface-container-lowest': 'var(--surface-container-lowest, #060e20)',
        'surface-container-low': 'var(--surface-container-low, #131b2e)',
        'surface-container': 'var(--surface-container, #171f33)',
        'surface-container-high': 'var(--surface-container-high, #222a3d)',
        'surface-container-highest': 'var(--surface-container-highest, #2d3449)',
        'on-surface': 'var(--on-surface, #dae2fd)',
        'on-surface-variant': 'var(--on-surface-variant, #bbcabf)',
        outline: 'var(--outline, #86948a)',
        'outline-variant': 'var(--outline-variant, #3c4a42)',
        primary: 'var(--primary, #4edea3)',
        'primary-container': 'var(--primary-container, #10b981)',
        'on-primary': 'var(--on-primary, #003824)',
        secondary: 'var(--secondary, #3b82f6)',
        'secondary-container': 'var(--secondary-container, #0566d9)',
        'on-secondary-container': 'var(--on-secondary-container, #e6ecff)',
        'status-online': 'var(--status-online, #10b981)',
        'status-fault': 'var(--status-fault, #f97316)',
        'status-offline': 'var(--status-offline, #64748b)',
        'electric-blue': '#3b82f6',
        apple: {
          blue: '#007AFF',
          'blue-dark': '#0A84FF',
          green: '#34C759',
          'green-dark': '#30D158',
          amber: '#FF9500',
          'amber-dark': '#FF9F0A',
          red: '#FF3B30',
          'red-dark': '#FF453A',
          purple: '#AF52DE',
          indigo: '#5856D6',
          teal: '#30B0C7',
          gray: {
            50: '#F9FAFB',
            100: '#F2F2F7',
            200: '#E5E5EA',
            300: '#D1D1D6',
            400: '#C7C7CC',
            500: '#8E8E93',
            600: '#636366',
            700: '#48484A',
            800: '#2C2C2E',
            900: '#1C1C1E',
            950: '#0B0C10',
          },
        },
      },
      fontFamily: {
        sans: ['-apple-system', 'BlinkMacSystemFont', '"SF Pro Text"', '"Inter"', 'Geist', '"Segoe UI"', 'sans-serif'],
        headline: ['-apple-system', 'BlinkMacSystemFont', '"SF Pro Display"', '"Inter"', 'Geist', 'sans-serif'],
        body: ['-apple-system', 'BlinkMacSystemFont', '"SF Pro Text"', '"Inter"', 'Geist', 'sans-serif'],
        mono: ['"SF Mono"', '"Geist Mono"', '"JetBrains Mono"', 'ui-monospace', 'monospace'],
      },
      borderRadius: {
        none: '0px',
        sm: '6px',
        DEFAULT: '8px',
        md: '10px',
        lg: '12px',
        xl: '16px',
        '2xl': '20px',
        '3xl': '24px',
        full: '9999px',
      },
      boxShadow: {
        'apple-sm': '0 2px 8px -2px rgba(0, 0, 0, 0.15), 0 1px 4px -1px rgba(0, 0, 0, 0.1)',
        'apple-md': '0 12px 24px -6px rgba(0, 0, 0, 0.25), 0 4px 12px -2px rgba(0, 0, 0, 0.15)',
        'apple-lg': '0 20px 32px -8px rgba(0, 0, 0, 0.35), 0 8px 16px -4px rgba(0, 0, 0, 0.2)',
        'apple-modal': '0 25px 50px -12px rgba(0, 0, 0, 0.5), 0 0 0 1px rgba(255, 255, 255, 0.1)',
      },
    },
  },
  plugins: [
    require('@tailwindcss/container-queries'),
  ],
};
